on: 
  push:
    branches:
      main
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.2
      with:
        ftp-server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: domains/code-solutions.tech/jpalmeidafotos/

        # server: ${{ secrets.ftp_host }}
        # username: ${{ secrets.ftp_user }}
        # password: ${{ secrets.ftp_password }}
        # server-dir: public_html/workspace
